name: k6 Test
on:
  push:
    branches:
      - main

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: |
            ./Load_Testing/8-dynamic-payload.js
